name: Build Client

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Create Gradle wrapper
        run: gradle wrapper

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Make JavaScript build scripts executable
        run: chmod +x CompileJS.sh MakeOfflineDownload.sh
        working-directory: target_teavm_javascript
        
      - name: Make WASM build scripts executable
        run: chmod +x CompileBootstrapJS.sh MakeWASMClientBundle.sh
        working-directory: target_teavm_wasm_gc

      - name: Build JavaScript client
        run: |
          ./CompileJS.sh
          ./MakeOfflineDownload.sh
        working-directory: target_teavm_javascript

      - name: Build WASM-GC client
        run: |
          ./CompileBootstrapJS.sh
          ./MakeWASMClientBundle.sh
        working-directory: target_teavm_wasm_gc

      - name: Get short commit hash
        id: vars
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Package artifacts
        run: |
          mkdir -p dist
          cp target_teavm_javascript/javascript/classes.js dist/classes.js
          cp target_teavm_javascript/javascript/assets.epk dist/assets.epk
          cp target_teavm_javascript/javascript/EaglercraftX_1.8_Offline_International.html dist/Eaglercraft_Offline_JS.html
          cp target_teavm_wasm_gc/javascript_dist/bootstrap.js dist/bootstrap.js
          cp target_teavm_wasm_gc/javascript_dist/assets.epw dist/assets.epw
          cp target_teavm_wasm_gc/javascript_dist/EaglercraftX_1.8_WASM-GC_Offline_Download.html dist/Eaglercraft_Offline_WASM.html
          cp src/web/index.html dist/index.html
          zip -r dist/dist.zip dist
          mkdir -p dist/rel
          cp dist/dist.zip dist/rel/dist_${{ steps.vars.outputs.hash }}.zip
          cp dist/Eaglercraft_Offline_JS.html dist/rel/Eaglercraft_Offline_JS.html
          cp dist/Eaglercraft_Offline_WASM.html dist/rel/Eaglercraft_Offline_WASM.html
          mkdir -p dist/web
          cp dist/index.html dist/web/index.html
          cp dist/classes.js dist/web/classes.js
          cp dist/assets.epk dist/web/assets.epk
          cp dist/bootstrap.js dist/web/bootstrap.js
          cp dist/assets.epw dist/web/assets.epw

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist_${{ steps.vars.outputs.hash }}
          path: dist/dist.zip

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.hash }}
          name: Release ${{ steps.vars.outputs.hash }}
          files: dist/rel/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/web
          publish_branch: gh-pages
          keep_files: false
